services:
  guacd:
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    user: root
    ports:
      - "4822:4822"
    volumes:
      - ./data/drive:/drive
      - guacd_record:/record
    environment:
      - GUACD_LOG_LEVEL=info

volumes:
  guacd_record:
